services:
  app:
    hostname: pw-scraper
    container_name: pw-scraper
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
